from __future__ import annotations

from typing import Protocol, Sequence

from core.contracts.analytics import InsightCard, TrendReportRef
from core.contracts.feedback import FeedbackRecord
from core.contracts.scene import SceneRef, SceneSummary


class L2AuditRepoPort(Protocol):
    def list_recent_decision_snapshots(self, limit: int = 50) -> Sequence[dict]: ...


    """Append-only. No update/delete in implementations."""
    def append_decision_snapshot(self, snapshot: dict) -> str: ...  # returns snapshot_id
    def append_scene_summary(self, summary: SceneSummary) -> str: ...
    def list_closed_scenes(self, channel: str, limit: int = 200) -> Sequence[SceneRef]: ...
    def read_scene_summary(self, scene_id: str) -> SceneSummary: ...


class L3LearningRepoPort(Protocol):
    """Batch/aggregate only."""
    def upsert_case_summary(self, case_summary: dict) -> None: ...
    def append_feedback(self, feedback: FeedbackRecord) -> None: ...
    def write_aggregate_metrics(self, metrics: dict) -> None: ...
    def read_aggregate_metrics(self, channel: str, period: str) -> dict: ...


class AnalyticsPort(Protocol):
    """Reads CLOSED-only summaries and produces non-actionable insights."""
    def generate_insights(self, period: str) -> Sequence[InsightCard]: ...
    def generate_reports(self, period: str) -> Sequence[TrendReportRef]: ...
