from __future__ import annotations
from core.contracts._compat import StrEnum


class RationaleCode(StrEnum):
    # Policy / escalation
    ACCUMULATION_ESCALATION = "ACCUMULATION_ESCALATION"
    CRITICAL_BY_POLICY_RULE = "CRITICAL_BY_POLICY_RULE"
    COOLDOWN_ACTIVE = "COOLDOWN_ACTIVE"
    TEMPORAL_TREND_WORSENING = "TEMPORAL_TREND_WORSENING"
    TEMPORAL_TREND_IMPROVING = "TEMPORAL_TREND_IMPROVING"

    # Signals (examples)
    HIGH_NEGATIVE_EMOTION = "HIGH_NEGATIVE_EMOTION"
    PERSISTENT_NEGATIVE_EMOTION = "PERSISTENT_NEGATIVE_EMOTION"
    UNCERTAINTY_ELEVATED = "UNCERTAINTY_ELEVATED"
    QUALITY_GATE_TRIGGERED = "QUALITY_GATE_TRIGGERED"

    # Governance / safety
    AUTO_INTERVENTION_BLOCKED = "AUTO_INTERVENTION_BLOCKED"
    CHILDCARE_HUMAN_REVIEW_REQUIRED = "CHILDCARE_HUMAN_REVIEW_REQUIRED"
    NO_ACTION_BY_POLICY = "NO_ACTION_BY_POLICY"
