# gatekit_template: lock-f4-submodule-hygiene-v1
name: Submodule Hygiene Gate
on:
  push:
    branches: [ "main" ]
  pull_request:
jobs:
  submodule-hygiene-gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Clone submodules without injected auth header
        run: |
          git config --global --unset-all http.https://github.com/.extraheader || true
          git config --local  --unset-all http.https://github.com/.extraheader || true
          git submodule sync --recursive
          git -c http.extraHeader= submodule update --init --recursive --depth=1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: python tools/gates/submodule_hygiene_gate.py --root .
