# gatekit_template: lock3-gate
name: lock3-gate

on:
  pull_request:
  workflow_dispatch:

jobs:
  lock3-gate:

    name: lock3-gate
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Detect LOCK-3 relevant changes
        id: changes
        shell: bash
        run: |
          set -euo pipefail
          BASE_SHA="${{ github.event.pull_request.base.sha }}"
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          echo "BASE_SHA=$BASE_SHA"
          echo "HEAD_SHA=$HEAD_SHA"

          git diff --name-only "$BASE_SHA" "$HEAD_SHA" > /tmp/changed_files.txt || true
          echo "Changed files:"
          sed -n '1,200p' /tmp/changed_files.txt || true

          if grep -Eq '^(var/audit/lock3_chain\.jsonl|audits/.*\.lock3\.json|docs/governance/contracts/|tools/audit/|tools/gates/|\.github/workflows/lock3-gate\.yml)' /tmp/changed_files.txt; then
            echo "relevant=true" >> "$GITHUB_OUTPUT"
          else
            echo "relevant=false" >> "$GITHUB_OUTPUT"
          fi

      - name: LOCK3_FASTPATH_SUMMARY
        shell: bash
        run: |
          set -euo pipefail
          echo "LOCK3_RELEVANT=${{ steps.changes.outputs.relevant }}"
          if [ "${{ steps.changes.outputs.relevant }}" != "true" ]; then
            echo "LOCK3_FASTPATH=SKIP_GATE_STEPS"
          else
            echo "LOCK3_FASTPATH=RUN_GATE_STEPS"
          fi
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip

      - name: Ensure audit chain file exists (fail-closed)
        if: steps.changes.outputs.relevant == 'true'
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f "var/audit/lock3_chain.jsonl" ]; then
            echo "FAIL-CLOSED: missing var/audit/lock3_chain.jsonl"
            exit 1
          fi

      - name: Run LOCK-3 Observer Gate
        if: steps.changes.outputs.relevant == 'true'
        shell: bash
        run: |
          set -euo pipefail
          python -m tools.gates.lock3_observer_gate \
            --path var/audit/lock3_chain.jsonl \
            --path var/observer/events.jsonl \
            --replay var/replay/packets.jsonl
