# gatekit_template: lock-f4-submodule-hygiene-v1
name: Submodule Hygiene Gate

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  submodule-hygiene-gate:
    name: submodule-hygiene-gate
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          persist-credentials: false
          fetch-depth: 1

      - name: clone submodules (auth via SUBMODULES_PAT)
        env:
          SUBMODULES_PAT: ${{ secrets.SUBMODULES_PAT }}
        run: |
          test -n "$SUBMODULES_PAT" || (echo "Missing SUBMODULES_PAT secret" && exit 1)
          git config --global url."https://${SUBMODULES_PAT}@github.com/".insteadOf "https://github.com/"
          git submodule sync --recursive
          git submodule update --init --recursive --depth=1

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: run submodule hygiene gate (fail-closed)
        run: python tools/gates/submodule_hygiene_gate.py --root .
